/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: polyman (https://sketchfab.com/Polyman_3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-iphone-15-pro-max-black-df17520841214c1792fb8a44c6783ee7
Title: Apple iPhone 15 Pro Max Black
*/

import * as THREE from 'three';
import React, { useEffect, useRef } from "react";
import { useGLTF, useTexture, } from "@react-three/drei";

function Model(props) {
  const { nodes, materials } = useGLTF("/models/scene.gltf");

  const texture = useTexture(props.item.img);

  const albedop = useTexture("/models/Plastic_color.jpg");
  const roup = useTexture("/models/Plastic_R.jpg");

  const naranja = useTexture("/models/Naranja_Color.jpg");
  const metal = useTexture("/models/Metal_Color.jpg");

  return (
    <group {...props} dispose={null}>



      <mesh
        castShadow
        receiveShadow
        geometry={nodes.xXDHkMplTIDAXLN.geometry}
        material={materials.pIJKfZsazmcpEiU}
        scale={-0.01}
      >
        <meshStandardMaterial roughness={1.3} map={texture}  emissiveMap={texture}  emissiveIntensity={0}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plastico.geometry}
        material={materials.eShKpuMNVJTRrgg}
        scale={-0.01}
      > 
        <meshStandardMaterial roughnessMap={roup}  map={albedop} metalness={0} />
      </mesh>

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Metales.geometry}
        material={materials.dxCVrUCvYhjVxqy}
        scale={-0.01}
      >

<meshStandardMaterial roughness={1} map={metal} metalness={1}  />
</mesh>
      <mesh
        castShadow
        receiveShadowS
        geometry={nodes.Naranjos.geometry}
        material={materials.hUlRcbieVuIiOXG}
        scale={-0.01}
      >
<meshStandardMaterial roughness={10} map={naranja}  />

      </mesh>



    </group>
  );
}

export default Model;

useGLTF.preload("/models/scene.glb");
